### PR TITLE
Fixed home page layout

### LINKED ISSUE #72: Main content is not centered in Firefox
The main content of the page is not centered when rendered in Firefox. It works correctly in Chrome and Opera. IE or Safari not checked.

### PR DESCRIPTION
**Pull request by frmdz**
**Before**:
Captura de pantalla_2020-03-03_23-56-53
Captura de pantalla_2020-03-03_23-57-36

**After:**

- Captura de pantalla_2020-03-03_23-46-35

- Captura de pantalla_2020-03-03_23-47-25

### CODE REVIEW

**Comment by enjolras** [comment]
Hi,

Thanks for your PR!

Now, a couple of comments on it :)

Before your patch, the wrong location of the homepage was, as far as I know, only happening in Firefox, for reasons that I have not investigated yet:

Chrome:
ojudge_chrome

Opera:
ojudge_opera

And, yes, Firefox:
ojudge_firefox

After your patch, a couple of problems arise:

- The fixed width of 1280px is lost. This is fixed by design, and that page width should be kept.
- The footer goes 'wild', doesn't stick to the bottom of the page when the contents don't fill the whole page vertically, and also shows some weird white margin on its bottom.
- The page doesn't behave as expected in neither chrome nor opera (can't check IE now).

Chrome, after:
ojudge_chrome_after

Opera, after:
ojudge_opera_after

Firefox, after:
ojudge_firefox_after

As you can see, the results are not the expected. To determine that this bug is fixed (I have created issue #72 for it), the behaviour in Firefox (i.e. main content centered) must be the same as in Chrome and Opera while keeping the fixed 1280px width and with the footer sticking to the bottom when vertical content doesn't fill the page and without white space below it.

Anyway, thanks again for taking an approach to it, please try to update your PR having the mentioned points in mind.

**Comment by frmdz** [comment]
I Fixed the "wild" footer and the centering problem, now works correctly. I think issue https://github.com/TheOnlineJudge/ojudge/issues/72 it's already solved.

Tested on Firefox:
Screen Shot 2020-03-05 at 04 42 01
Screen Shot 2020-03-05 at 04 42 29
And Chrome:
Captura de pantalla_2020-03-05_04-38-01
Captura de pantalla_2020-03-05_04-39-24

**Comment by frmdz** [comment]
I still need to work on the responsiveness tho.

**Comment by frmdz** [comment]
The horizontal responsiveness it's working now.

Firefox:
Screen Shot 2020-03-05 at 06 05 28
Screen Shot 2020-03-05 at 06 05 50

Chrome:
Captura de pantalla_2020-03-05_06-03-31
Captura de pantalla_2020-03-05_06-04-04

**Comment by frmdz** [comment]
I Fixed the "wild" footer and the small space, also fixed the centered layout and width.

P.S Reload with ctrl + F5 or delete the cache.

Tested on Firefox:
Captura de pantalla_2020-03-05_06-42-39
Captura de pantalla_2020-03-05_06-43-15

and Chrome:
Captura de pantalla_2020-03-05_06-43-59
Captura de pantalla_2020-03-05_06-44-18

**Comment by enjolras** [comment]
Nice improvment, but not there yet. Now the footer appears correctly in place, but if the page content is bigger than the browser area, no scrollbars appear and the content is truncated:

Screenshot_20200306_135525

The expected results should look like:

Screenshot_20200306_135800

Screenshot_20200306_135817

Almost there, but some more work is needed. Thanks!

**Comment by frmdz** [comment]
Fixed with the latest commit. (i hope so...)

Chrome:
Captura de pantalla_2020-03-06_20-18-16
Captura de pantalla_2020-03-06_20-18-37
Captura de pantalla_2020-03-06_20-19-14

Firefox:
Screen Shot 2020-03-06 at 20 35 18

Screen Shot 2020-03-06 at 20 35 33

Screen Shot 2020-03-06 at 20 35 35

**Comment by enjolras** [comment]
Merge into main

**Comment by enjolras** [comment]
Still leaves a 2 pixel gap between footer and browser canvas, but will be treated as issue #75 , so we can move forward with this one. Great work!

**Pull request merged**
